const Head = () => {
    return (
      <>
        <title> Travel Expert</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </>
    )
  }

  export default Head;